### ISSUE TITLE
Position relative to the circle's center

### ISSUE THREAD

**Issue by iddan** [datatypesjs/circle-sector#2]
I tried using circle-sector for generating a pie-chart like graph. But, because the sectors generated by the library are all aligned to the top left corner I was not able to make it work.

I would like to have an option to specify the alignment like so: (inspired by css transform)

```JavaScript
const circleSector = new CircleSector({
    align: 'center',
});

**Comment by adius** [comment]
Just generate the pie graph in the top left corner and translate it to the center.

```svg
<g id="pieChart" transform="translate(x, y)">
  <!-- segments -->
</g>
```

This is much cleaner than translating every segment separately.

**Comment by iddan** [comment]
The thing is that to translate it by myself I have to calculate the distance between the segment to the circle center.

**Comment by adius** [comment]
? ... you simply translate the piechart by it's radius. So actually it is `transform="translate(radius, radius)`

**Comment by iddan** [comment]
My bad, I forgot I can rotate the sector to the desired degree to be part of the circle and translate it.
