### ISSUE TITLE
Provide a UMD module

### ISSUE THREAD

**Issue by iddan** [datatypesjs/circle-sector#3]

**Comment by adius** [comment]
Sorry, but this is not going to happen. CommonJS / native modules bundled with browserify / rollup / webpack is the right way to go!

**Comment by iddan** [comment]
Agree, but when using tools like CodePen unfortunately you can use npm modules (yet) how about providing [unpkg](https://unpkg.com) link instead?

**Comment by adius** [comment]
I recommend using https://esnextb.in 😉
